### PR TITLE
Added more logging and more customizable options

### PR DESCRIPTION
**Pull request by vedharish**
This is considerable code change. Please test this further.

### CODE REVIEW

**Comment by ohcibi** [comment]
I'll have a look at it as soon as I have time. Could you make a simpler pr that only synchronizes this package with the changes mentioned in https://github.com/browserstack/browserstack-testem-integration/issues/6 in the meantime?

It would also be great if you'd provide a better commit message, explaining in more detail what you've changed. Simply force push to your branch to update this pr.

**Comment by vedharish** [comment]
Updated the commit message.

Regarding a simpler PR, I am afraid that this is an atomic change. This change basically passes the command line arguments to the respective scripts to the constructor/functions that the scripts basically use.

`start-BrowserStackLocal` uses `browserstacktunnel-wrapper` npm packages and its command line arguments are passed on to the tunnel constructor. Similarly with the `run_on_browserstack` script and `browserstack` npm package.
In the master branch, none of these settings are configurable.
Also I added logs at different steps. In the master branch it only logs the line - `tunnel connected` when the tunnel connects.

I have mentioned the particular usage of the scripts and all the options that are supported in-depth in the `README.md` file. Please check it out and take your time to understand the code. Just comment here if anything is unclear to you.

**Comment by vedharish** [comment]
Also you need to bump the package version to republish it on npmjs.org. The typo in package.json corrected in the last commit isn't yet reflected in the npm module.

Preferably, create a new commit which just bumps the package version after you merge in any pull requests and then republish it on npmjs.org.

Cheers 🍺

**Comment by ohcibi** [comment]
Lets not mix those things up. The initial issue that you created on the original repo was about hanging tests which could be solved by replacing `command` with `exe`, wasn't it? As this regards only a sample file in this project, there shouldn't be any problems with the changes in this pr? This pr could still rename `testem.json` to `testem-sample.json` while having `exe` instead of `command` in it. Or am I missing something?

**Comment by vedharish** [comment]
This PR doesn't solve the "Hang after tests finish" situation. This PR concerns "Added more logging and more customizable options" as the PR title and commit message suggests.

Now, there are 4 issues mentioned in "initial issue" ie [this issue](browserstack/browserstack-testem-integration#6).
1. Test hang issue -
   
   This was resolved by changing `command` in testem.json to `exe`. Now, this is not required on all   systems. The issue as mentioned in testem/testem#739, was that child_process.exec behaves differently   on different systems. So, the binary process that is run is not killed properly on some systems (example    ubuntu systems on circleci). @alexlafroscia had this issue but the currently, I think, he has the issues 3   and 4 mentioned below.
   
   Please tell us if you have the "tests hang" issue too (after trying both `command` and `exe`) and mention the system you are using it on. But please do so on the main issue page.
2. Typo in package.json -
   
   You merged the pull request that corrected this. But you still need to publish the package, so that `npm install` downloads the package with this changes
3. `testem.js not found?` issue -
   
   This issue still needs to be debugged. This PR doesn't solve this issue.
4. `times out after 300 seconds of "inactivity"` issue -
   
   300 seconds is the default value timeout(IDLE_TIMEOUT) for javascript workers on BrowserStack. This is configurable, as I mentioned and needs to be added [here](https://github.com/ohcibi/browserstack-testem-integration/blob/b46ec6a70c2839f023ed49b6c86e18a8464303ca/run_on_browserstack.js#L46).
   This is what this PR does. As mentioned in the commit message, it "exposes browserstacktunnel-wrapper and browserstack package-specific options via command-line arguments.". In this case, you can use `--timeout <time>` as an argument to `run_on_browserstack`

If you have any of the above issues, please mention on the main issues page, if you have some other issue related to running testem tests on browserstack, create a new issue on the browserstack/browserstack-testem-integration repo. 

This PR tackles how to pass on configuration parameters to respective modules that it uses. Lets just discuss any issues related to that on this page. 

I understand that you are happy with how things work as it is in the master branch. If you don't think that this PR is a significant enhancement, just close this PR.

**Comment by ohcibi** [comment]
Don't get me wrong. I think this pr is relevant, but I don't have the time to test this now. Independently from this, I'd like this package to be in sync with the original one, that's all.

**Comment by ohcibi** [comment]
> You merged the pull request that corrected this. But you still need to publish the package, so that npm install downloads the package with this changes

thanks for pointing this out. Its my first npm package 8-). I've published it now.

**Comment by ohcibi** [comment]
@vedharish i just realized that I've mixed up the two of you 8-). I thought you were the other guy and he actually said that he wanted to look into the changes I was talking about, so just forget about that 8-).

Regarding the changes from this PR: don't you think those are useful for the example-repo as well?

**Comment by vedharish** [comment]
@ohcibi Yes, you are correct. We published a new npm package [here](https://www.npmjs.com/package/browserstack-jstesting-cli).
We will make it an official package from BrowserStack and update the original example-repo to use that package instead.

Thanks!

**Pull request closed without merging**
