### PR TITLE
Fix typo in path to executable

### PR DESCRIPTION
**Pull request by alexlafroscia**

### CODE REVIEW

**Comment by ohcibi** [comment]
Thanks man!

**Comment by alexlafroscia** [comment]
Sure thing! Been trying to get BrowserStack + Testem playing nice for testing an Ember app, this repo has been really useful.

**Comment by ohcibi** [comment]
I've made it to use it in my own ember projects 8-).

**Comment by alexlafroscia** [comment]
Do you get an issue where the tests hang after completing?  I've been banging my head against that problem for too long...

Also: I've been thinking about trying to turn this into a proper Ember CLI addon.  I'll let you know if that comes together :smile:

**Comment by ohcibi** [comment]
I've run into this independently from browserstack but I don't know what has caused this. It feeled like reinstalling everything helped, but you never know...

**Comment by alexlafroscia** [comment]
I've been having a conversation with the BrowserStack people over [here](https://github.com/browserstack/browserstack-testem-integration/issues/6) which seems to think that `command` should be replaced with `exe`.  If I can get a version of this config working with that setup, I'll PR those changes, too.

**Comment by ohcibi** [comment]
I've just merged the latest changes from the original repo. It seems to work out but I don't have the time to test it. It'd be great if you could do that and make the PR

**Pull request merged**
